# Generated by Django 4.2.3 on 2023-08-04 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.CharField(default='NA', max_length=400),
            preserve_default=False,
        ),
    ]
